---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - wireguard
      - wireguard-tools
      - ufw
    state: present

- name: Generate server private key
  shell: wg genkey | tee /etc/wireguard/server_private.key
  args:
    creates: /etc/wireguard/server_private.key
  register: server_private_key

- name: Generate server public key
  shell: echo "{{ server_private_key.stdout }}" | wg pubkey | tee /etc/wireguard/server_public.key
  args:
    creates: /etc/wireguard/server_public.key
  register: server_public_key

- name: Generate client private key
  shell: wg genkey | tee /etc/wireguard/client_private.key
  args:
    creates: /etc/wireguard/client_private.key
  register: client_private_key

- name: Generate client public key
  shell: echo "{{ client_private_key.stdout }}" | wg pubkey | tee /etc/wireguard/client_public.key
  args:
    creates: /etc/wireguard/client_public.key
  register: client_public_key

- name: Configure WireGuard server
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'

- name: Configure WireGuard client
  template:
    src: client.conf.j2
    dest: /etc/wireguard/client.conf
    mode: '0600'

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Configure UFW
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: "22", proto: "tcp" }
    - { port: "{{ wireguard_port }}", proto: "udp" }

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Start and enable WireGuard
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: yes

- name: Fetch client configuration
  fetch:
    src: /etc/wireguard/client.conf
    dest: client.conf
    flat: yes
